"""
ai_service.py (Trecho) - ai_assistant function
"""
import json
from typing import Dict, Optional
from google import genai
from google.genai import types


class AIService:
    # ----------------------------------------------------
    # TOOL: ai_assistant (Assistente de Chat)
    # ----------------------------------------------------
    def ai_assistant(self, user_question: str, context_data: Optional[Dict] = None) -> str:
        """
        Answer questions from the user about finances, using contextual data.
        
        Args:
            user_question: The user's question (e.g., "Why is my Grocery budget in red?").
            context_data: Financial data retrieved from other services (Budget/Analytics).
            
        Returns: The response generated by the AI model.
        """
        
        if not self.client: 
            return "Ai assistant unavailable. Please check the API credentials."
        
        # 1. Prepare the Context
        # Convert the dictionary of data (expenses, budgets) into a JSON string readable by the AI
        context_str = json.dumps(context_data or {})
        
        # 2. Get the System Instruction (to maintain financial focus)
        # The system prompt ensures that the AI acts as a financial advisor.
        system_instruction = self.prompts.format("ai_assistant_system")
        
        # 3. Create the Final Prompt
        user_prompt = (
            f"User Question: {user_question}\n"
            f"Context Data (Expenses/Budgets): {context_str}\n\n"
            "Please answer concisely and usefully, referencing the provided data."
        )

        # 4. Call the Gemini API
        response = self.client.models.generate_content(
            model=self.model,
            contents=user_prompt,
            config=types.GenerateContentConfig(
                temperature=0.3, # Keep temperature low for factual responses
                system_instruction=system_instruction
            )
        )

        return response.text